version: "3"
services:
  node:
    image: "node:14-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - PATH=$PATH:/home/node/app/node_modules/.bin
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:3000"
    command: "npm start"